### ISSUE TITLE
Currently the library does not work due to changes in the Cleverbot "API"

### ISSUE THREAD

**Issue by mattijv** [folz/cleverbot.py#13]
Currently the library does not work. The Cleverbot server responds with a 404 and the bot returns an empty string.

I did a Lua client for Cleverbot based on this library and was recently notified by users that it had stopped working. I found out that Cleverbot has begun to require a cookie to be send with the request headers. This cookie is set when visiting the cleverbot.com website. A quick fix is to add

`'Cookie': 'XVIS=TEI939AFFIAGAYQZ'`

to the request headers.

This however is a temporary measure, as the cookie might change at a later date. A more robust way would be to request the Cleverbot homepage when creating an instance of the class and setting the cookie based on the response.

**Comment by folz** [comment]
Thanks for the heads up and suggested fix. I'll work on it.

**Comment by ionuthulub** [comment]
Done. Thank you @mattijv for the bug report.

**Comment by EhsanKia** [comment]
Seems like it broke again? Might need to implement the more robust solution.

**Comment by ionuthulub** [comment]
>> Cleverbot #1: Hi.
>> Cleverbot #2: What are you doing?
>> Cleverbot #1: Talking to you.
>> Cleverbot #2: Are you having fun?
>> Cleverbot #1: That depends on you.
>> Cleverbot #2: How does it depend on me?
>> Cleverbot #1: It depends on what you decide.

It looks like it's working.
It's true that it will start responding with advertising messages after a while, but that's a different problem. 
The more robust solution has already been implemented.
