### ISSUE TITLE
python 3 modules and unicode encoding hashing

### ISSUE THREAD

**Issue by cxlai** [folz/cleverbot.py#17]
Had some trouble getting this to work (and am still having trouble). Since Python 3 has changed some of its modules, namely http.cookiejar, urllib2, urllib.parse... the __init__ in cleverbot.py causes errors during import. I also got a Unicode-object must be encoded before hashing error that I'm trying to fix.

I don't know much about Python so I'm really have some trouble. Any tips on how to fix the unicode error?

**Comment by norwack** [comment]
Use Python 2. Nobody likes Python 3 anyway.

**Comment by folz** [comment]
...I like python 3

**Comment by folz** [comment]
I don't do too much with this library anymore but I've always wanted to
learn six, so I'll take a look at adding py2&3 compatibility over the
weekend.

**Comment by JohnPhamous** [comment]
Has this been updated to py3?

**Comment by Delivator** [comment]
I don't think :/

**Comment by folz** [comment]
Thanks for the comment - I got inspired and worked on some py2/py3 compatibility stuff this weekend. I'll push to a branch soon(tm). If this is something you want, comment in the thread so you get notified / give me motivation.

**Comment by JohnPhamous** [comment]
Yes! If you need help I can give it a shot too.

**Comment by folz** [comment]
Hi - please check out #19 and see if it works for you under python 2 and 3.

**Comment by folz** [comment]
(also @cxlai - give http://stackoverflow.com/questions/7585307/typeerror-unicode-objects-must-be-encoded-before-hashing a read)

**Comment by Delivator** [comment]
Umlauts don't work correctly!
Instead of "ß" i get  "`&szlig;`" the html code i think!

**Comment by folz** [comment]
(oops, fat-fingered the close button)

@Delivator - Does that behavior happen on the version that's currently on pypi (aka, before my py3 changes)?

**Comment by Delivator** [comment]
Idk and i don't want to install python2 just for tesing :/

**Comment by folz** [comment]
For sure, I'll check it out on my end.

**Comment by folz** [comment]
Fixed with #19. Thanks for opening the issue!
