### ISSUE TITLE
Getting an "IndexError: list index out of range"

### ISSUE THREAD

**Issue by jcapron** [folz/cleverbot.py#22]
I'm using cleverbot for my Hipchat bot and today we noticed it didn't reply anymore. After upgrading the python module, I get this error:

```
In [1]: from cleverbot import Cleverbot

In [2]: cb = Cleverbot()

In [3]: cb.ask("hi")
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-f21b82920051> in <module>()
----> 1 cb.ask("hi")

/Library/Python/2.7/site-packages/cleverbot/cleverbot.py in ask(self, question)
     95         self.conversation.append(question)
     96 
---> 97         parsed = self._parse(resp.text)
     98 
     99         # Set data as appropriate

/Library/Python/2.7/site-packages/cleverbot/cleverbot.py in _parse(resp_text)
    147             ]
    148 
--> 149         if parsed[0][1] == 'DENIED':
    150             raise CleverbotAPIError()
    151 

IndexError: list index out of range

In [4]: 
```

Thanks for your help!

**Comment by mrgigabyte** [comment]
You're not the only one who's facing this issue :/ I apparently tried and read the code and printed the output i was receiving. Well apparently it is returning "DENIED" perhaps it detected that the requests are made by the bot. I will probably see a workaround this issue.

**Comment by basvdwollenberg** [comment]
```
Cleverbot tries to prevent unauthorized access to its API by
obfuscating how it generates the 'icognocheck' token. The token is
currently the md5 checksum of the 10th through 36th characters of the
encoded data. This may change in the future.
```
This is probably the issue I guess.

**Comment by folz** [comment]
PR #23 by @NyanKiyoshi may have fixed the issue you're having. Check for the most recent version of this library on pypi, v1.0.1, and let me know if this is still a problem.

**Comment by jcapron** [comment]
@folz thanks! As you said, PR https://github.com/folz/cleverbot.py/pull/23 fixed it!
Closing the issue.

**Comment by OOrks** [comment]
Bump
