### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by mrgigabyte** [folz/cleverbot.py#25]
Ah appears like the API has stopped again, i did print the response it was getting and here's a screenshot of  resp_text.

Thanks! 
![screenshot from 2016-05-16 18-57-05](https://cloud.githubusercontent.com/assets/18233002/15290711/00f9f9d4-1b98-11e6-91bb-c0a7127fc67d.png)

**Comment by TomG777** [comment]
For me the code stopped working too. I was able to fix it by changing the variable `RESOURCE = "/webservicemin"` with `RESOURCE = "/webservicemin?uc=165&"`
Digging a bit through the js code on cleverbot.com showed me they added the uc=165& part to the makeAIRequestBody function. And adding this to the url used in the post seems to fix it for me.

**Comment by notstevek** [comment]
Can confirm what @TomG777 said is working.

cd /usr/local/lib/python3.4/dist-packages/cleverbot
sudo nano cleverbot.py

![image](https://cloud.githubusercontent.com/assets/7034850/15300019/b2c0cba8-1b74-11e6-8368-1f0b9fcc40b4.png)

**Comment by mrgigabyte** [comment]
10/10 worked like a charm! thanks

**Comment by folz** [comment]
After merging #26 I'm unable to push to pypi for some reason. It's my school's graduation weekend so I don't have too much time to look into this, but you can set your requirements to the git tag "v1.0.2" for now.

Here's my traceback, if any of you know recognize the issue and can recommend a fix. AFAIK I haven't done anything to my environment other than pulling PR #26.

```
(cleverbot)➜  cleverbot.py git:(master) python setup.py sdist upload
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running sdist
running check
warning: sdist: standard file not found: should have one of README, README.txt

reading manifest template 'MANIFEST.in'
writing manifest file 'MANIFEST'
creating cleverbot-1.0.2
creating cleverbot-1.0.2/cleverbot
making hard links in cleverbot-1.0.2...
hard linking LICENSE -> cleverbot-1.0.2
hard linking README.md -> cleverbot-1.0.2
hard linking setup.py -> cleverbot-1.0.2
hard linking cleverbot/__init__.py -> cleverbot-1.0.2/cleverbot
hard linking cleverbot/cleverbot.py -> cleverbot-1.0.2/cleverbot
creating dist
Creating tar archive
removing 'cleverbot-1.0.2' (and everything under it)
running upload
Submitting dist/cleverbot-1.0.2.tar.gz to https://pypi.python.org/pypi
HTTP Error 400: Invalid URI: u'UNKNOWN'
error: HTTP Error 400: Invalid URI: u'UNKNOWN'
(cleverbot)➜  cleverbot.py git:(master) python --version            
Python 3.4.3
(cleverbot)➜  cleverbot.py git:(master) pip freeze      
astroid==1.4.4
colorama==0.3.6
coverage==4.0.3
future==0.15.2
lazy-object-proxy==1.2.1
pluggy==0.3.1
py==1.4.31
pylint==1.5.4
pytest==2.8.7
requests==2.9.1
six==1.10.0
tox==2.3.1
virtualenv==14.0.3
wrapt==1.10.6
```

**Comment by edwardslabs** [comment]
https://bitbucket.org/pypa/pypi/issues/452/http-error-400-invalid-uri-uunknown

**Comment by folz** [comment]
Thanks for the link @edwardslabs, I'll try that when I get home this evening.

**Comment by jcapron** [comment]
Thanks @folz! Meanwhile, upgrading via the git tag works perfectly.
```
pip install git+git://github.com/folz/cleverbot.py.git@v1.0.2
```

**Comment by folz** [comment]
Hey all - the instructions from @edwardslabs worked and v1.0.2 is now on pypi!

Please **uninstall the git-tag version** and reinstall from pypi so you continue to receive updates.
