### ISSUE TITLE
I would write the error/issue here but I don't even know what to say...

### ISSUE THREAD

**Issue by GusCaplan** [folz/cleverbot.py#28]
```py
from cleverbot import Cleverbot
```
produces:
```
Noob bot is connected
Noob bot's name is: GusBot
```
Also it is stuck there. It is like something isn't closing. Also, what's with Noob bot and all that and why????
also, if i run this in a python shell, it works.
if i try to import cleverbot in a script, it does this.

**Comment by folz** [comment]
Could you link the repository or gist the code you're using? Or is just the line, `from cleverbot import Cleverbot`, enough to produce that output?

If the latter, it's probably something in the script or your python environment, as there is nothing in the code that would print those lines out.

**Comment by GusCaplan** [comment]
@folz it is literally just that one line, which is why I am so confused.

**Comment by edwardslabs** [comment]
@GusCaplan Googling the output you are getting pointed me here: http://pastebin.com/tvRDiVui

Does that look familiar to you? Also something similar seems to be here: https://github.com/ImthePeach/UtilityBot/blob/master/bot.py

**Comment by TomG777** [comment]
The output you are getting seems to be from your discord bot. Assuming that is the code where you are running it in.
The problem that there is no additional output is because you aren't parsing a question to cleverbot. As given in the [example usage](https://github.com/folz/cleverbot.py/blob/master/cleverbot/cleverbot.py#L21) you need some more stuff.
You could do something like:
```python
@bot.command()
async def cleverbot(question : str):
    """Ask a question to cleverbot"""
    answer = cb.ask(question)
    await bot.say(answer')
```
With `cb = Cleverbot()` near the start of your file. This is assuming you want it to be a command for your bot.
I myself do not use the discord library like this so it might need some tweaking to get it right but I think this is the right way.

**Comment by GusCaplan** [comment]
no no no. If i open terminal and type "python" and then put `from cleverbot import Cleverbot` all is well.
if i make a python script (lets call it cbtest.py) and put NOTHING EXCEPT `from cleverbot import Cleverbot` i get the weird thing.

p.s. i am trying to make a cleverbot, but this issue got in my way.

**Comment by edwardslabs** [comment]
From the python console please execute:

```
>>> import sys
>>> print(sys.path)
```

Then paste the same into test.py and run it. Please paste the results from each in here.

**Comment by folz** [comment]
Since this is likely a problem with the path, I'm going to close this issue. Feel free to reopen if you think it's a bug with cleverbot.py after all.

**Comment by GusCaplan** [comment]
from console:
```
['', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/duckduckgo2-0.242-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/python_dateutil-2.0-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urwid-1.3.1-py3.5-macosx-10.6-intel.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dnsimple-0.3.6-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ratelimit-1.0.1-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python35.zip', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages']
```

from script:
```
['/Users/Gus', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/duckduckgo2-0.242-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/python_dateutil-2.0-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urwid-1.3.1-py3.5-macosx-10.6-intel.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dnsimple-0.3.6-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ratelimit-1.0.1-py3.5.egg', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python35.zip', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages']
```

diff:
the first string in the list is empty in console, and has `/Users/Gus/` in a script. That is all.

**Comment by GusCaplan** [comment]
@folz how would the path change how cleverbot is working?

**Comment by edwardslabs** [comment]
@GusCaplan I believe what is likely happening here is you have a script in /Users/Gus named cleverbot.py that contains the discord bot code. By default python will search the current first for modules to import which is why your bot script is getting imported. Try renaming cleverbot.py to something else and then running your test script.

**Comment by GusCaplan** [comment]
@edwardslabs I'm not using any discord things for these scripts. My test script literally is empty except for `from cleverbot import Cleverbot`.

**Comment by edwardslabs** [comment]
@GusCaplan from a terminal please `ls -l /Users/Gus` your simple script is importing a file from your home directory and not from one of the other paths. To prove this I bet if you moved the script to a new empty directory and run it there you will not see the same behavior.
