### ISSUE TITLE
Index out of range in _parse

### ISSUE THREAD

**Issue by zylozs** [folz/cleverbot.py#29]
I am working on a discord bot which is using cleverbot.py in a plugin to add support to the chat. It was working roughly a month ago when I last messed with cleverbot specifically, but recently i've been getting an error when trying to use it. As far as i'm aware, nothing has changed and this error has popped up. 

I am running Arch Linux and using python 3.5.

My input was just 'hi', but it has the same problem regardless of the input. cb is my cleverbot instance.

```
 File "/home/vince/repos/StyroBotpy/dist/plugins/cleverbotchat.py", line 32 in executeCommand  
   response = self.cb.ask(parameters)  
 File "/usr/lib/python3.5/site-packages/cleverbot/cleverbot.py", line 104, in ask  
   parsed = self._parse(resp.text)  
 File "/usr/lib/python3.5/site-packages/cleverbot/cleverbot.py", line 156, in _parse  
   if parsed[0][1] == 'DENIED':  
 IndexError: list index out of range
```

**Comment by jeffjnh** [comment]
Just got this from the error issue list...

**Comment by jeffjnh** [comment]
I'm having the same problem as well... with anything that I input in 2.7

**Comment by BobbyJohansen** [comment]
This is because the api came back with a 404 not found when posting. The API seems to have changed? Will dig deeper.

**Comment by edwardslabs** [comment]
Are you using the latest version (1.0.2) It is working fine for me.

**Comment by zylozs** [comment]
My pip has 1.0.1 installed and i've tried updating it but it doesn't go to 1.0.2. How would i fix this?

**Comment by Brennan-VanderLaan** [comment]
Pip is pulling down 1.0.1 at the moment - needs to be updated

**Comment by edwardslabs** [comment]
In #25 there was an issue trying to update the version on pypi. If you run 

`git clone https://github.com/folz/cleverbot.py`
`cd cleverbot.py`
`python cleverbot.py/setup.py install`

That should install the latest version.

**Comment by folz** [comment]
At the moment it's not on pypi - you can install at git tag v1.0.2.

Google for "pip install git tag" for more information.

**Comment by folz** [comment]
See also #25

**Comment by zylozs** [comment]
installing the tag fixed it. Thanks!

**Comment by folz** [comment]
Hey all - v1.0.2 is now on pypi!

Please **uninstall the git-tag version** and reinstall from pypi so you continue to receive updates.
