### ISSUE TITLE
Cleverbot doesn't work anymore? :(

### ISSUE THREAD

**Issue by jacopomarcovaldi** [folz/cleverbot.py#30]
Hi, i try to use human demo and i got this error:

>> You: ciao                                                                                                             
Traceback (most recent call last):                                                                                       
  File "human_bot_chat.py", line 21, in <module>                                                                         
    main()                                                                                                               
  File "human_bot_chat.py", line 15, in main                                                                             
    answer = cleverbot_client.ask(question)                                                                              
  File "/usr/local/lib/python2.7/dist-packages/cleverbot/cleverbot.py", line 104, in ask                                 
    parsed = self._parse(resp.text)                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/cleverbot/cleverbot.py", line 156, in _parse                              
    if parsed[0][1] == 'DENIED':                                                                                         
IndexError: list index out of range 

Cleverbot api are changed? Can you help me?
Thank you

**Comment by brandonsturgeon** [comment]
I just confirmed that Cleverbot is working.

`if parsed[0][1] == 'DENIED':`

This is where your error is coming from, I imagine your data isn't nested like you're expecting it to be. Litter some prints around and you'll find your problem.

**Comment by jacopomarcovaldi** [comment]
Hi, here you can find the answer of cleverbot:

<html>                                                                                                                   
<head><title>404 Not Found</title></head>                                                                                
<body bgcolor="white">                                                                                                   
<center><h1>404 Not Found</h1></center>                                                                                  
<hr><center>nginx/1.6.2 (Ubuntu)</center>                                                                                
</body>                                                                                                                  
</html>

**Comment by folz** [comment]
Which version of the cleverbot package are you using? I believe they recently changed their service url.

**Comment by jacopomarcovaldi** [comment]
Yes you right, i update cleverbot url and now it works :)
