### ISSUE TITLE
Access denied.

### ISSUE THREAD

**Issue by Zygimantass** [folz/cleverbot.py#35]
`Traceback (most recent call last):
  File "C:/Users/Zygimantas/Projects/CleverTwitchBot/main.py", line 65, in <module>
    parseCommand(message, user, chat, s)
  File "C:/Users/Zygimantas/Projects/CleverTwitchBot/main.py", line 37, in parseCommand
    commands[command](user, message)
  File "C:/Users/Zygimantas/Projects/CleverTwitchBot/main.py", line 44, in clever
    chat(s, cb.ask(message.split(" ")[1:]))
  File "C:\Python27\lib\site-packages\cleverbot\cleverbot.py", line 104, in ask
    parsed = self._parse(resp.text)
  File "C:\Python27\lib\site-packages\cleverbot\cleverbot.py", line 159, in _parse
    if parsed[0][1] == 'DENIED':
IndexError: list index out of range`

`<HTML><BODY>DENIED</BODY></HTML>`

This is what the Cleverbot API returns

**Comment by folz** [comment]
What version of python and cleverbot.py are you using? What is RESOURCE set to in your copy of cleverbot.py (https://github.com/folz/cleverbot.py/blob/master/cleverbot/cleverbot.py#L30)?

**Comment by folz** [comment]
What version of python and cleverbot.py are you using? What is RESOURCE set to in your copy of cleverbot.py (https://github.com/folz/cleverbot.py/blob/master/cleverbot/cleverbot.py#L30)?

**Comment by Zygimantass** [comment]
I now copied the code from Github and it works 50%

**Comment by Zygimantass** [comment]
It doesnt work from a function, but when I run it at the start of the code it works perfectly

My code:

http://pastebin.com/pfEvtWML

**Comment by Zygimantass** [comment]
I'm using Py2.7 and the latest version of Cleverbot my resource is set to: "/webservicemin?uc=165&"

**Comment by Zygimantass** [comment]
Issue closed, problem on my part
