### ISSUE TITLE
Multiple conversations?

### ISSUE THREAD

**Issue by TheKyu** [folz/cleverbot.py#36]
I'm running the bot in another bot with multiple users at the same time. I was wondering whether I could have multiple conversations going on at the same time

like `cleverbot.ask(question, conversationid=x)`

**Comment by folz** [comment]
Create multiple Cleverbot objects, like

conversations = [
  Cleverbot(),
  Cleverbot(),
  Cleverbot()
]

Each instance is it's own conversation.
