### ISSUE TITLE
Null response

### ISSUE THREAD

**Issue by MrSmorez** [folz/cleverbot.py#37]
Using cleverbot.py 1.1.0 and Python 3.5.1
```python
from cleverbot import Cleverbot
cb = Cleverbot()
cb.ask("hi")
```
gives a null response "".

**Comment by limshuen** [comment]
I went to cleverbot.com and it seems they changed their request link to `http://www.cleverbot.com/webservicemin?uc=321&`
To change it for the library:
```
cd /usr/local/lib/python3.5/dist-packages/cleverbot
sudo nano cleverbot.py
```
On line 30, `RESOURCE = "/webservicemin?uc=165&" `
I changed it to `RESOURCE = "/webservicemin?uc=321&"` and it seems to have fixed it. Hope this helps!

**Comment by MrSmorez** [comment]
Thank you! Fix worked.

**Comment by folz** [comment]
Thank you for reporting this! I'll have an update on pypi shortly.
