### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gstewart86** [folz/cleverbot.py#40]
Good Afternoon,

It looks like there might've been a change on the Cleverbot side - I'm seeing the 'ask' method fail like so:
>>> import cleverbot
>>> clev = cleverbot.Cleverbot()
>>> clev.ask("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cleverbot.py", line 104, in ask
    parsed = self._parse(resp.text)
  File "cleverbot.py", line 156, in _parse
    if parsed[0][1] == 'DENIED':
IndexError: list index out of range
>>> exit()

If I can provide any further information please feel free to let me know.

Thanks

**Comment by folz** [comment]
Hey there - your problem should be fixed if you update to v1.1.1 on pypi. Let me know if that works for you, thanks!
