### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Vadyy** [folz/cleverbot.py#41]
![image](https://cloud.githubusercontent.com/assets/20133506/20800141/1d9f8620-b7ed-11e6-9e4b-e3d2c29ab63d.png)
started happening recently

**Comment by TomG777** [comment]
Updating to V1.1.1 should fix your problem.

**Comment by Vadyy** [comment]
hmm, I did just check pip and it didn't have anything to update

**Comment by TomG777** [comment]
What is the version number when running `pip show cleverbot`

**Comment by Vadyy** [comment]
Hmm, it's 1,1,0, strange

**Comment by TomG777** [comment]
Make sure you use the `--upgrade` argument,

`pip install --upgrade cleverbot`

**Comment by Vadyy** [comment]
Thanks, that worked and fixed it!
