### ISSUE TITLE
Chatting in Specific Language

### ISSUE THREAD

**Issue by utkusen** [folz/cleverbot.py#42]
We can select a specific language on cleverbot.com however this library does not provide this feature. Is Cleverbot's API doesn't support this or not included in this library?

**Comment by folz** [comment]
Currently unsupported - the data that this library sends to Cleverbot was taken from a browser set to en_US. If you can inspect your browser and see what the difference is between what you send vs this library sends, we can add support for different languages.

**Comment by utkusen** [comment]
Hello

In my browser, POST request of a chat message is like that:

```
POST /webservicemin?uc=3210&botapi=see%20www.cleverbot.com%2Fapis& HTTP/1.1
Host: www.cleverbot.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3
Referer: http://www.cleverbot.com/
Content-Length: 137
Content-Type: text/plain;charset=UTF-8
Cookie: XVIS=TEI939AFFIAGAYQZ; _cbsid=-1; __qca=P0-477073472-1485031506035; CBCC=y; __utma=223276361.686415963.1485031857.1485031857.1485031857.1; __utmb=223276361.1.10.1485031857; __utmc=223276361; __utmz=223276361.1485031857.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1
Connection: close

stimulus=Merhaba.&cb_settings_language=tr&cb_settings_scripting=no&islearning=1&icognoid=wsf&icognocheck=f6d0aeab055e91a180452fa62828a9e8
```

It seems `cb_settings_language` parameter defines the language. I hope this is helpful

**Comment by folz** [comment]
Closing as this project is now unmaintained - see https://github.com/edwardslabs/cleverwrap.py for a Python library to access the official API.
