### ISSUE TITLE
Being able to use the tweaks

### ISSUE THREAD

**Issue by Luigimaster1** [folz/cleverbot.py#46]
If you didn't know, "tweaks" are to change how Cleverbot acts.
Scales:
Sensible to Wacky
Shy to Talkative
Self centered to Attentive

But anyways, currently there isn't support for it. Maybe there can be...?

**Comment by folz** [comment]
Closing as this project is now unmaintained - see https://github.com/edwardslabs/cleverwrap.py for a Python library to access the official API.
