### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Atomicbeast101** [folz/cleverbot.py#49]
List index out of range happens when I use the cleverbot API, assuming CleverBot API got changed again. Here's the error log:
```  
File "/usr/local/lib/python3.5/dist-packages/cleverbot/cleverbot.py", line 125, in ask 
    parsed = self._parse(resp.text)
File "/usr/local/lib/python3.5/dist-packages/cleverbot/cleverbot.py", line 173, in _parse
    if parsed[0][1] == 'DENIED':
IndexError: list index out of range
```

Currently using Python v3.5.2 and Cleverbot v2.0.0

**Comment by mrgigabyte** [comment]
facing the same issue :(

**Comment by JoeBanks13** [comment]
I think this is an issue with cleverbot as a lot of programs I have written have stopped working

**Comment by zenrac** [comment]
Same

**Comment by folz** [comment]
Cleverbot recently changed their API policies to limit to 5k free calls per month, and have an official REST api. See https://www.cleverbot.com/api/#abovetitle

**Comment by Beefywhale** [comment]
Same :/ Will this get fixed? :cry:

**Comment by zenrac** [comment]
It must be never fixed, because it was an unofficial lib, and now there is an official. We can't use the unofficial anymore anymore

**Comment by folz** [comment]
I mean I'm down to turn this into a wrapper for the official API but it'll take longer than a one-line change (which is all that was required when things broke in the past). In the meantime / if you can't wait, the link above a good place to start writing your own code.

**Comment by mrgigabyte** [comment]
https://github.com/mrgigabyte/cleverbot.py you can checkout this, i have already initiated a pull request. Just for those who missed that.

**Comment by Woopydo** [comment]
With the above hack, cb = Cleverbot('ERASE ANYTHING HERE')

**Comment by zenrac** [comment]
I think this hack don't work anymore

**Comment by EhsanKia** [comment]
Hmm, kinda annoying that we have to sign up for an API key, but at least there's an official API and it'll no longer break due to them trying to get rid of abuser who probably destroy their servers. I don't know about the other people here but 5000 a month is reasonable and enough for my use.

It should also be fairly easy to integrate as there's no more hacky cookie/header stuff. I can code a PR up this weekend if no one else has time for it.

**Comment by mrgigabyte** [comment]
https://github.com/mrgigabyte/cleverbot.py/commit/1e8b2a18bf2b9d74230488564b38f33b3568a4cb
this works for now

**Comment by JoeBanks13** [comment]
Does the boibot.com hack still work??

**Comment by millerhooks** [comment]
This might help y'all. The API is a lot simpler now.

https://gist.github.com/millerhooks/2db94c841603aea58cec31e668c7f501

**Comment by EhsanKia** [comment]
@mrgigabyte But that's boibot no? Isn't that an entirely different bot? I haven't tried it but is it comparable in quality to cleverbot?

@millerhooks thanks! Though it seems you pasted twice, might want to edit/fix that.

**Comment by JoeBanks13** [comment]
I don't know what boibot actually is but I edited cleverbot.py's code to use it so now all my cleverbot scripts still work, it is just as good in comparison to cleverbot in my opinion

**Comment by mrgigabyte** [comment]
If you would have tried digging in a bit, you would have figured the answer to the question yourself. 
Boibot is a bot made my the very same team ( cleverbot ) 
so yeah.

**Comment by edwardslabs** [comment]
I went ahead and wrote a wrapper for the new API: https://github.com/edwardslabs/cleverwrap.py feel free to use it as you please.

**Comment by Delivator** [comment]
+1

**Comment by folz** [comment]
Closing as this project is now unmaintained - see https://github.com/edwardslabs/cleverwrap.py for a Python library to access the official API.
