### ISSUE TITLE
api key support

### ISSUE THREAD

**Issue by notstevek** [folz/cleverbot.py#52]
Looks like they updated to require an api key.

I grabbed one and replaced my-app in Cleverbot('my-app') with the the key but still no luck.

`Traceback (most recent call last):
  File "test.py", line 3, in <module>
    cb.ask("Hi. How are you?")
  File "/usr/local/lib/python3.4/dist-packages/cleverbot/cleverbot.py", line 125, in ask
    parsed = self._parse(resp.text)
  File "/usr/local/lib/python3.4/dist-packages/cleverbot/cleverbot.py", line 173, in _parse
    if parsed[0][1] == 'DENIED':
IndexError: list index out of range
`

**Comment by olivierverwoerd** [comment]
If I remember correctly
The Cleverbot('my-app') wasn't made for the api key. 

The current cleverbot DOES NOT WORK!
You can try alternatives or wait for someone to fix this.

**Comment by edwardslabs** [comment]
http://www.cleverbot.com/api/wrappers has a list of wrappers that will work with the new api system.

**Comment by folz** [comment]
Closing as this project is now unmaintained - see https://github.com/edwardslabs/cleverwrap.py for a Python library to access the official API.
